### ISSUE TITLE
Game keeps resetting city shield placement every turn

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#387]
In just one city.

**Comment by AlexFolland** [comment]
I am guessing this happens when an enemy unit is near that city.  Was an enemy unit near that city?

Anyway, this doesn't happen in Civilization unless the enemy unit ends its turn on top of a worker-assigned tile, and Civilization only relocates that one tile to the most optimal tile among available tiles.

**Comment by kazgaroth011** [comment]
No enemy was there. I placed production from 3 tiles to 3 other tiles and the game resets this every turn. This didn't happen in my 2nd city.

**Comment by SWY1985** [comment]
The mechanism is still not working correctly... sorry about that. At the moment, the game resets the resources when an enemy is moving nearby. This is obviously not correct. I will try to implement it more like @AlexFolland says here.
