### ISSUE TITLE
Game crashes after renaming city

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#449]
After giving city a short name (e.g. R), and exiting and entering the city repeatedly, eventually the game crashes. Strangely this didn't happen when I gave it a longer name (or it could be I just didn't test it often enough).

**Comment by SWY1985** [comment]
I am unable to reproduce this, do you have any more details on how to reproduce? Did you see an error message?
Maybe, in order to catch the error, you need to open a command prompt and run the game from there:

![image](https://user-images.githubusercontent.com/9248547/33309289-e7b710b6-d41d-11e7-9492-73e61e998468.png)

**Comment by kazgaroth011** [comment]
Here's a screenshot of what I get after error & zip file.
[settings.zip](https://github.com/SWY1985/CivOne/files/1510608/settings.zip)
![capture7](https://user-images.githubusercontent.com/21365802/33330072-2a34df8c-d45e-11e7-95dc-01cbbbfb3142.PNG)

Tried it few more time and again this happens only with short city names. Rename a city with 1 or 2 characters and try exiting & entering city a few times. This is when the crash happens.

**Comment by SWY1985** [comment]
It happens when you have a unit from a short city name in the city. I can fix it. Thank you!
